#name of website (in header)
name: CoderDojo-Hawthorn
#short description
description: CoderDojo is a global free movement for children from 7 to 17 years of age to learn coding. 
Such coding languages include:  Python, Javascript and more.
# twitter/facebook/instagram (social media)
